### ISSUE TITLE
chapter_exe単体で動作させるとAviSynthがエラーを吐いて止まる

### ISSUE THREAD

**Issue by kimityan555** [tobitti0/chapter_exe#4]
チャプターを拾う部分だけ使いたくて、chapter_exeだけビルドしました。
`chapter_exe -v test.ts -o test.txt-m 10 -s 10`と実行したのですが、

> Loading plugins.
Avisynth ERROR: unexpected character ""
(test.ts, line 1, column 1)
Avisynth ERROR: unexpected character ""
(test.ts, line 1, column 1)
Error: No Audio!

のようなエラーが出てしまい原因がわかりません。
test.tsはBS11にて放送されたアニメで、ファイル名が長ったらしいのでtestにしています。
別のファイル（NHKのニュース番組の録画）だとunexpected charctor "@"と若干変わりますが同じく動作しませんでした。

元のtsファイルに対してなにか下処理が必要なのでしょうか？

**Comment by kimityan555** [comment]
冷静になってreadmeを読むと動画ファイルを直接指定できないと書いてありました。
L-SMASH-Worksの導入で躓いていまだ成功はしていませんが、chapter_exe側の問題ではないと分かったので大丈夫です。

失礼しました。

**Comment by tobitti0** [comment]
@kimityan555 
返信遅くなりすみません。
お察しの通り、tsファイルを直接指定することはできません。

`test.avs`というものを作っていただき、（avsなら名前は何でも良いですが）
```
TSFilePath="test.ts"
LWLibavVideoSource(TSFilePath, repeat=true, dominance=1)
AudioDub(last,LWLibavAudioSource(TSFilePath, stream_index=1, av_sync=true))
```
このような形で内容を記載します。
この書き方だと、動作に`L-SMASH-Works`が必要です。
実行は下記のように行います。
`/chapter_exe -v test.avs -s 8 -e 4 -o test.txt`
（数字などはお好みです。）

また、既知の問題として、`L-SMASH-Works`が`1170.0.0.0`より新しいものだと`chapter_exe`が動作しないことが報告されています。

下記もご確認いただけると参考になるかもしれません。
https://github.com/tobitti0/JoinLogoScpTrialSetLinux/issues/20
